### PR TITLE
Fix image distortion

### LINKED ISSUE #116: Fix image distortions
Screen Shot 2020-07-20 at 12 56 37 PM
Screen Shot 2020-07-20 at 12 56 22 PM

### PR DESCRIPTION
**Pull request by JPI-Tech**
Fixed image distortion closes #116

### CODE REVIEW

File: src/sections/Hero.js [hunk 1]
```diff
@@ -76,7 +76,9 @@ class Hero extends Component {
                             md={{ order: 2 }}
                             xs={{ order: 1 }}
                         >
-                            <ImageContainer src={HeroGraphic} alt='Hero Graphic' />
+                            <div>
+                                <ImageContainer mx-auto src={HeroGraphic} alt='Hero Graphic' />
```
Comment (otech47) [inline src/sections/Hero.js:80]: Did you mean to add this as a className? If not remove
